# Generated by Django 4.2.7 on 2023-11-22 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_posts_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 22, 10, 16, 54, 567366)
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="slug",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="posts",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
