# Generated by Django 4.2.7 on 2023-11-24 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_posts_date_alter_posts_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 24, 9, 29, 16, 530644)
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
