# Generated by Django 4.2.7 on 2023-12-04 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_posts_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, unique=True
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="password",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="posts",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 4, 8, 51, 28, 24865)
            ),
        ),
    ]
